# Generated by Django 3.2 on 2021-05-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage_place',
            old_name='place_id',
            new_name='garage_id',
        ),
        migrations.RenameField(
            model_name='garage_place',
            old_name='place_name',
            new_name='garage_name',
        ),
    ]
